name: Coverity
on:
  push:
    branches: [ master, stage, 'releases/**' ]
  pull_request:
    branches: [ master, stage, 'releases/**' ]
  workflow_dispatch:

jobs:
  Coverity:

    runs-on: self-hosted

    env:
      COV_URL: ${{ secrets.COV_URL }}
      COV_USER: ${{ secrets.COV_USER }}
      COVERITY_PASSPHRASE: ${{ secrets.COVERITY_PASSPHRASE }}
      COVERITY_PATH: ${{ secrets.COV_PATH }}
      COVERITY_PROJECT: cpp-helloworld
      BLDCMD: gcc .\hello-world.cpp -lstdc++ -o helloworld
      CHECKERS: --all --enable-constraint-fpp --enable-fnptr --enable-virtual

    steps:
    - name: Coverity Full Scan
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        set -x
        cov-build --dir idir $BLDCMD
        cov-analyze --dir idir $CHECKERS --ticker-mode none --strip-path $GITHUB_WORKSPACE $CHECKERS
        cov-commit-defects --dir idir --ticker-mode none --url $COV_URL --stream $COVERITY_PROJECT-${GITHUB_REF##*/} 

    # - name: Coverity Quality Gate
    #   if: ${{ github.event_name != 'pull_request' }}
    #   run: |
    #     curl -fLsS --user $COV_USER:$COVERITY_PASSPHRASE $COV_URL/api/viewContents/issues/v1/OWASP%20Web%20Top%2010?projectId=$COVERITY_PROJECT > results.json
    #     if [ $(cat results.json | jq .viewContentsV1.totalRows) -ne 0 ]; then cat results.json | jq .viewContentsV1.rows; exit 1; fi

    - id: changeset
      name: Get Pull Request Changeset
      uses: jitterbit/get-changed-files@v1
      if: ${{ github.event_name == 'pull_request' }}

    - name: Coverity Incremental Scan
      if: ${{ github.event_name == 'pull_request' && steps.changeset.outputs.added_modified != '' }}
      run: |
        set -x
        cov-run-desktop --dir idir --url $COV_URL --stream $COVERITY_PROJECT-$GITHUB_BASE_REF --build $BLDCMD
        cov-run-desktop --dir idir --url $COV_URL --stream $COVERITY_PROJECT-$GITHUB_BASE_REF --present-in-reference false \
          --ignore-uncapturable-inputs true --exit1-if-defects true ${{ steps.changeset.outputs.added_modified }}
