name: Coverity
on:
  push:
    branches: [ master, stage, 'releases/**' ]
  pull_request:
    # branches: [ master, stage, 'releases/**' ]
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  Coverity:
    runs-on: self-hosted
    environment: tenju-test

    env:
      COV_URL: ${{ secrets.COV_URL }}
      COV_USER: ${{ secrets.COV_USER }}
      COVERITY_PASSPHRASE: ${{ secrets.COVERITY_PASSPHRASE }}
      COVERITY_PATH: ${{ secrets.COV_PATH }}
      COVERITY_PROJECT: cpp-helloworld
      BLDCMD: gcc .\hello-world.cpp -lstdc++ -o helloworld
      CHECKERS: --all --enable-constraint-fpp --enable-fnptr --enable-virtual

    steps:
    - uses: actions/checkout@v2
    - name: Coverity Full Scan
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        cov-build --dir idir gcc .\hello-world.cpp -lstdc++ -o helloworld
        cov-analyze --dir idir --all --enable-constraint-fpp --enable-fnptr --enable-virtual --ticker-mode none 
        cov-commit-defects --dir idir --ticker-mode none --url $env:COV_URL --stream $env:COVERITY_PROJECT-main

    - name: Coverity Quality Gate
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        curl -fLsS --user $env:COV_USER:$env:COVERITY_PASSPHRASE $env:COV_URL/api/viewContents/issues/v1/High%20Impact%20Outstanding?projectId=$env:COVERITY_PROJECT > results.json
        if ($(cat results.json | jq .viewContentsV1.totalRows) -ne 0 ); then cat results.json | jq .viewContentsV1.rows; exit 1; fi

    - id: changeset
      name: Get Pull Request Changeset
      uses: jitterbit/get-changed-files@v1
      if: ${{ github.event_name == 'pull_request' }}

    - name: Coverity Incremental Scan
      if: ${{ github.event_name == 'pull_request' && steps.changeset.outputs.added_modified != '' }}
      run: |
        cov-run-desktop --dir idir --url $env:COV_URL --stream $env:COVERITY_PROJECT-$GITHUB_BASE_REF --build gcc .\hello-world.cpp -lstdc++ -o helloworld
        cov-run-desktop --dir idir --url $env:COV_URL --stream $env:COVERITY_PROJECT-$GITHUB_BASE_REF --present-in-reference false \
          --ignore-uncapturable-inputs true --exit1-if-defects true ${{ steps.changeset.outputs.added_modified }}
